[package]
name = "falcon-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
falcon-storage = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
toml = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }

[dev-dependencies]
rcgen = { version = "0.14.8", default-features = false, features = ["pem", "ring"] }
tempfile = "3"
